---
title: "R Notebook"
output: html_notebook
---



```{r}
rm(list = ls(all.names =TRUE))
str(murders)
```


```{r}
head(murders)
```


```{r}
tail(murders)
```


```{r}
a <- murders$abb
a
class(a)
b <- murders[["abb"]]
b
identical(a,b)
```


```{r}
x <- factor(murders$region)
levels(x)
nlevels(x)
```


```{r}
table(murders$region)
```


```{r}
temp <- c("Beijing"=35,"Lagos" = 88, "Paris"=42, "Rio de Janeiro" =84, "San Juan" = 81, "Toronto" = 30)
temp
class(temp)
```


```{r}
city <- c("Beijing","Lagos" , "Paris", "Rio de Janeiro", "San Juan" , "Toronto" )
city
class(city)
```


```{r}
d <- temp[1:3]
d
```


```{r}
y <- temp[c(3,5)]
y
```


```{r}
z <-temp["Beijing"]
z
```


```{r}
s <- c(12:73)
s
class(s)
```


```{r}
a <- seq (1,10,0.5)
a
class(a)
```


```{r}
b <- seq(1,10)
b
class(b)
```


```{r}
x <- c("1","3","5")
x <- as.integer(x)
class(x)
```


```{r}
df <- data.frame(name = c('Anastasia','Dima','Katherine','James','Emily','Michael','Matthew','Laura','Kevin','Jonas'),
                 score = c(12.5,9,16.5,12,9,20,14.5,13.5,8,19),
                 attempts = c(1, 3, 2, 3, 2, 3, 1, 1, 2, 1),
                 qualify= c('yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'))
df
```


```{r}
str(df)
```


```{r}
summary(df)
```


```{r}
x <- df [c(3,5),c(1,3)]
x
```


